# 配置服务端口号
server:
  port: 10200

## 配置数据库的连接信息
spring:
  application:
    name: spzx-cloud-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spzx-cloud-order?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    openfeign:
      client:
        config:
          default:
            logger-level: full
            read-timeout: 2000
            connect-timeout: 2000
            retryer: com.atguigu.cloud.config.FeignClientRetryer

# 配置mybatis的相关信息
mybatis-plus:
  type-aliases-package: com.atguigu.cloud.entities
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    com.atguigu.cloud.apis.UserFeignClient: debug
 
